name: inventai-be

on:
  push:
    branches: main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup VENV
        run: pip3 install virtualenv

      - name: Activate VENV
        run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt

      - name: Zip Dependencies
        run: |
          cd ./venv/lib/python3.11/site-packages
          zip -r9 ../../../../app.zip .
      - name: Add App to Zip
        run: cd ./app && zip -g ../app.zip -r .

      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app.zip
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - name: Download Lambda app.zip
        uses: actions/download-artifact@v2
        with:
          name: app
      - name: Upload to S3
        run: aws s3 cp app.zip s3://inventai-be/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name inventai-be --s3-bucket inventai-be --s3-key app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
